### ISSUE TITLE
@typescript-eslint 버전오류

### ISSUE THREAD

**Issue by Hansanghyeon** [Hansanghyeon/linter#17]
```
"@typescript-eslint/eslint-plugin": "^8.0.0-alpha.41",
"@typescript-eslint/parser": "^8.0.0-alpha.41",
```

```log
[Info  - 오후 1:43:27] ESLint server is starting.
[Info  - 오후 1:43:27] ESLint server running in node v20.11.1
[Info  - 오후 1:43:27] ESLint server is running.
[Info  - 오후 1:43:27] ESLint library loaded from: /root/tools/eslint-config/test/node_modules/eslint/lib/api.js
2024-07-13T13:43:27.695Z eslint:eslint Searching for eslint.config.js
2024-07-13T13:43:27.697Z eslint:eslint Loading config from /root/tools/eslint-config/test/eslint.config.mjs
2024-07-13T13:43:27.697Z eslint:eslint Config file URL is file:///root/tools/eslint-config/test/eslint.config.mjs
2024-07-13T13:43:28.090Z eslint:rules Loading rule 'consistent-return' (remaining=289)
2024-07-13T13:43:28.095Z eslint:rules Loading rule 'dot-notation' (remaining=288)
2024-07-13T13:43:28.097Z eslint:rules Loading rule 'init-declarations' (remaining=287)
2024-07-13T13:43:28.098Z eslint:rules Loading rule 'max-params' (remaining=286)
2024-07-13T13:43:28.104Z eslint:rules Loading rule 'no-dupe-class-members' (remaining=285)
2024-07-13T13:43:28.105Z eslint:rules Loading rule 'no-empty-function' (remaining=284)
2024-07-13T13:43:28.111Z eslint:rules Loading rule 'no-invalid-this' (remaining=283)
2024-07-13T13:43:28.112Z eslint:rules Loading rule 'no-loop-func' (remaining=282)
2024-07-13T13:43:28.112Z eslint:rules Loading rule 'no-loss-of-precision' (remaining=281)
2024-07-13T13:43:28.113Z eslint:rules Loading rule 'no-magic-numbers' (remaining=280)
2024-07-13T13:43:28.123Z eslint:rules Loading rule 'no-restricted-imports' (remaining=279)
2024-07-13T13:43:28.149Z eslint:rules Loading rule 'no-unused-expressions' (remaining=278)
2024-07-13T13:43:28.150Z eslint:rules Loading rule 'no-useless-constructor' (remaining=277)
2024-07-13T13:43:28.154Z eslint:rules Loading rule 'prefer-destructuring' (remaining=276)
[Info  - 오후 1:43:28] Server process exited successfully
[Error - 오후 1:43:28] Calculating config file for file:///root/tools/eslint-config/test/src/test.ts) failed.
ConfigError: Config (unnamed): Key "plugins": Cannot redefine plugin "@typescript-eslint".
    at rethrowConfigError (/root/tools/eslint-config/test/node_modules/@eslint/config-array/dist/cjs/index.cjs:303:8)
    at /root/tools/eslint-config/test/node_modules/@eslint/config-array/dist/cjs/index.cjs:1098:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfigWithStatus (/root/tools/eslint-config/test/node_modules/@eslint/config-array/dist/cjs/index.cjs:1091:43)
    at FlatConfigArray.getConfig (/root/tools/eslint-config/test/node_modules/@eslint/config-array/dist/cjs/index.cjs:1120:15)
    at ESLint.calculateConfigForFile (/root/tools/eslint-config/test/node_modules/eslint/lib/eslint/eslint.js:1187:24)
    at async ESLint.isPathIgnored (/root/tools/eslint-config/test/node_modules/eslint/lib/eslint/eslint.js:1209:24)
    at async /root/.vscode-server/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js:1:24295
    at async Object.M [as withClass] (/root/.vscode-server/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js:1:19807)
    at async O.then.m.validate (/root/.vscode-server/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js:1:24255)
2024-07-13T13:43:28.503Z eslint:eslint Searching for eslint.config.js
2024-07-13T13:43:28.503Z eslint:eslint Loading config from /root/tools/eslint-config/test/eslint.config.mjs
2024-07-13T13:43:28.503Z eslint:eslint Config file URL is file:///root/tools/eslint-config/test/eslint.config.mjs
2024-07-13T13:43:28.503Z eslint:eslint Linting complete in: 0ms
```

**Comment by Hansanghyeon** [comment]
`@typescript-eslint@^8.0.0` 나오기전까지는 버전업 금지

**Comment by Hansanghyeon** [comment]
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.0.0
